---
name: "CI"
on: [push]

jobs:
  build_test:
    name: Build & Test
    runs-on: macos-11
    env:
        DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Test
        run: swift test -v
