---
name: "CI"
on: [push]

jobs:
  build-test:
    runs-on: macos-11.0
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}

      - name: Check out
        uses: actions/checkout

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
